---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Stat ~/.local/share/lunarvim/lvim
    stat:
      path: ~/.local/share/lunarvim/lvim
    register: lunarvim_exists
