---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:

    - name: Check if nvim is installed
      command: which nvim
      changed_when: false
      failed_when: nvim_installed.rc not in [0,1]
      register: nvim_installed

    - name: Return fail if it is not installed
      fail:
        msg: "nvim is not installed, install first"
      when: nvim_installed.rc not in [ 0 ]
